### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Germey** [xiyouMc/WebHubBot#35]
2018-01-21 15:24:48 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.pornhub.com/embed/ph59a628740c49c> (referer: https://www.pornhub.com/)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/Library/Python/2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/Library/Python/2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/Library/Python/2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Library/Python/2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/private/var/py/WebHubBot/PornHub/PornHub/spiders/pornHubSpider.py", line 59, in parse_ph_info
    _ph_info_json = json.loads(_ph_info[0])
IndexError: list index out of range

![](https://ws1.sinaimg.cn/large/006tNc79ly1fno9h25m0gj314k0qy45i.jpg)

**Comment by afetmin** [comment]
我也是这问题，估计页面变了，可能要把正则重写一下

**Comment by Blavtes** [comment]
in pornHubSpider.py 
line 56 =>:
        _ph_info = re.findall('var flashvars =(.*?),\n', selector.extract())

**Comment by xiyouMc** [comment]
可以尝试分析下。 应该就是正则变掉了。

**Comment by rover5056** [comment]
也是这个问题  
正在分析中
@xiyouMc

**Comment by xiyouMc** [comment]
@rover5056  刚合并了一个修复这块的 PR ,麻烦你这边 pull 测试下 同时把结果同步过来。

**Comment by ceilwoo** [comment]
出现同样问题

**Comment by shellteo** [comment]
我也是这个问题

**Comment by antushengcui** [comment]
目前还是不行，正则化怎么搞
