### ISSUE TITLE
运行错误.怎么解决..

### ISSUE THREAD

**Issue by wiiii** [xiyouMc/WebHubBot#36]
D:\Develop\PythonSpace\WebHubBot\PornHub\PornHub\spiders\pornHubSpider.py:4: ScrapyDeprecationWarning: Module `scrapy.spider` is deprecated, use `scrapy.spiders` instead
  from scrapy.spider import CrawlSpider
2018-02-07 00:14:28 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: PornHub)
2018-02-07 00:14:28 [scrapy.utils.log] INFO: Overridden settings: {'BOT_NAME': 'PornHub', 'CONCURRENT_REQUESTS': 20, 'DEPTH_PRIORITY': 1, 'DOWNLOAD_DELAY': 1, 'FEED_FORMAT': 'CSV', 'FEED_URI': '/Users/xiyouMc/Documents/pornhub.csv', 'NEWSPIDER_MODULE': 'PornHub.spiders', 'REDIRECT_ENABLED': False, 'ROBOTSTXT_OBEY': True, 'SCHEDULER_DISK_QUEUE': 'scrapy.squeues.PickleFifoDiskQueue', 'SCHEDULER_MEMORY_QUEUE': 'scrapy.squeues.FifoMemoryQueue', 'SPIDER_MODULES': ['PornHub.spiders']}
2018-02-07 00:14:28 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
Unhandled error in Deferred:
2018-02-07 00:14:28 [twisted] CRITICAL: Unhandled error in Deferred:

2018-02-07 00:14:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "D:\Develop\mzitu\venv\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\crawler.py", line 77, in crawl
    self.engine = self._create_engine()
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\crawler.py", line 102, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\core\engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "D:\Develop\mzitu\venv\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "D:\Develop\mzitu\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Develop\PythonSpace\WebHubBot\PornHub\PornHub\middlewares.py", line 3, in <module>
    from user_agents import agents
ModuleNotFoundError: No module named 'user_agents'

**Comment by xiyouMc** [comment]
user_agents 组件是 user_agents.py 文件，可以查看下这个文件是否存在。 其次尝试把 from user_agents import agents 改为 from ./user_agents import agents

**Comment by xlmitang** [comment]
我也遇到了这个问题，user_agents.py文件是存在的。
尝试把 from user_agents import agents 改为 from ./user_agents import agents
提示如下错误：

  File "D:\py\WebHubBot\PornHub\PornHub\middlewares.py", line 3
    from ./user_agents import agents
          ^
SyntaxError: invalid syntax
