### ISSUE TITLE
首次运行报错了。

### ISSUE THREAD

**Issue by bingoku** [xiyouMc/WebHubBot#42]
```
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    cmdline.execute("scrapy crawl pornHubSpider".split())
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/cmdline.py", line 148, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/crawler.py", line 243, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/crawler.py", line 134, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/crawler.py", line 330, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/Users/nibuw/.pyenv/versions/WebHub/lib/python2.7/site-packages/scrapy/utils/misc.py", line 63, in walk_modules
    mod = import_module(path)
  File "/Users/nibuw/.pyenv/versions/2.7.13/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named PornHub.spiders
```

**Comment by swiftPeter** [comment]
me too ,the same error

**Comment by madonhe** [comment]
same error
my delete __init__.py after than
[root@localhost WebHub]# python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    cmdline.execute("scrapy crawl pornHubSpider".split())
  File "/usr/lib64/python2.7/site-packages/scrapy/cmdline.py", line 110, in execute
    settings = get_project_settings()
  File "/usr/lib64/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/lib64/python2.7/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named WebHub.settings

**Comment by madonhe** [comment]
是不是版本不同，加载包的方式发生了变化。
[root@localhost app]# scrapy version -v
Scrapy       : 1.5.0
lxml         : 4.2.1.0
libxml2      : 2.9.8
cssselect    : 1.0.3
parsel       : 1.4.0
w3lib        : 1.19.0
Twisted      : 17.9.0
Python       : 2.7.5 (default, Aug  4 2017, 00:39:18) - [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
pyOpenSSL    : 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018)
cryptography : 2.2.2
Platform     : Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core

**Comment by xiyouMc** [comment]
项目结构变了下， 同步一下就好了。

**Comment by dengbaoling** [comment]
怎么同步

**Comment by xiyouMc** [comment]
@dengbaoling rebase
