### ISSUE TITLE
AttributeError: 'FeedExporter' object has no attribute 'slot'

### ISSUE THREAD

**Issue by partyspy** [xiyouMc/WebHubBot#54]
```
2018-07-18 21:15:31 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ?.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x10460a5d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 220, in item_scraped
    slot = self.slot
AttributeError: 'FeedExporter' object has no attribute 'slot'
```

**Comment by githubPsearth** [comment]
我也是这个问题

**Comment by tuojiaotuojiao** [comment]
me too
